config/routes.rb
Rails.application.routes.draw do
  get "/first", to: "site#first", as: :first_page
  get "/second", to: "site#second", as: :second_page
  post "/third", to: "site#third", as: :third_page
  get "/fourth", to: "site#fourth", as: :fourth_page
  root "site#first"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  # after_create_commit do
  #   broadcast_update_to("teststr",
  #     target: "broadcasts",
  #     html: "Post #{title} was created."
  #   )
  # end

  # after_update_commit do
  #   broadcast_prepend_to("teststr",
  #     target: "broadcasts",
  #     html: "<div>[#{Time.now}] UPDATE: Changed title to #{title}</div>".html_safe
  #   )
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def first
    @count = 3
  end

  def second
  end

  def third
    @name, @email, @age = params[:person].values_at(:name, :email, :age)
    @count = params[:count].to_i + 1
    @post = Post.create(title: @name)
    @post.broadcast_prepend_to("teststr", target: "broadcasts")
  end

  def fourth; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
NEW POST: <%= post.title %>

app/views/site/first.html.erb
<h1>Site#first</h1>
<p>Find me in app/views/site/first.html.erb</p>

<div id="someid" data-controller="test" data-test-myelement-class="bg-black mt-4"
      data-test-name-value="John" data-test-age-value="25">
  <input type="text" data-test-target="text" />
  <button data-action="click->test#hello">Click Me!</button>
</div>

<%= link_to "Second", second_page_path %>

app/views/site/fourth.html.erb
<%= turbo_frame_tag "fourthid" do %>
  <hr />
  This content was loaded from a different template.
<% end %>

app/views/site/second.html.erb
<h1>Site#second</h1>
<p>Find me in app/views/site/second.html.erb</p>

<%= turbo_frame_tag "someid" do %>
  Hello!
<% end %>

<%= turbo_frame_tag "formid" do %>
  Something else
<% end %>

app/views/site/third.turbo_stream.erb
<%= turbo_stream.prepend "people" do %>
  <tr>
    <td><%= @name %></td>
    <td><%= @email %></td>
    <td><%= @age %></td>
  </tr>
<% end %>

<%= turbo_stream.replace "hidden-counter" do %>
  <%= hidden_field_tag :count, nil, id: "hidden-counter", value: @count %>
<% end %>

<%= turbo_stream.update_all ".counter" do %>
  <%= @count %>
<% end %>